apiVersion: v1
kind: Service
metadata:
  name: {{ include "abune-server.fullname" . }}
  labels:
    {{- include "abune-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  ports:
    - name: game-server
      port: {{ .Values.service.ports.server.internalPort }}
      {{ if eq .Values.service.type "NodePort" }}
      targetPort: {{ .Values.service.ports.server.internalPort }}
      nodePort: {{ .Values.service.ports.server.externalPort }}
      {{ end }}
      protocol: UDP      
    - name: akka-cluster
      port: {{ .Values.service.ports.cluster.internalPort }}
      {{ if eq .Values.service.type "NodePort" }}
      targetPort: {{ .Values.service.ports.cluster.internalPort }}
      nodePort: {{ .Values.service.ports.cluster.externalPort }}
      {{ end }}
      protocol: TCP   
  selector:
    {{- include "abune-server.selectorLabels" . | nindent 4 }}
